/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Class.Petugas;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Hilman
 */
public class frmEditPetugas extends javax.swing.JDialog {
    Petugas db = new Petugas();
    public void setForm(Petugas p){
        tkdpetugas.setText(p.getKdPetugas());
        tnamapetugas.setText(p.getPetugas());
        cbjkpetugas.setSelectedItem(p.getJk());
        tnotelp.setText(p.getNo_telp());
        talamat.setText(p.getAlamat());
        tpassword.setText(p.getPassword());
    }
    /**
     * Creates new form frmEditPetugas
     */
    public frmEditPetugas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tpassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbjkpetugas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tblbatal = new javax.swing.JButton();
        tkdpetugas = new javax.swing.JTextField();
        tblsimpan = new javax.swing.JButton();
        tnamapetugas = new javax.swing.JTextField();
        tnotelp = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Petugas");

        jLabel2.setText("Nama Petugas");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("No Telepon");

        cbjkpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Kelamin", "L", "P" }));

        jLabel5.setText("Alamat");

        jLabel7.setText("EDIT DATA PETUGAS");

        jLabel6.setText("Password");

        tblbatal.setText("Batal");
        tblbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblbatalActionPerformed(evt);
            }
        });

        tkdpetugas.setEditable(false);

        tblsimpan.setText("Simpan");
        tblsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tblsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(tblbatal))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbjkpetugas, 0, 188, Short.MAX_VALUE)
                            .addComponent(tkdpetugas)
                            .addComponent(tnotelp)
                            .addComponent(tnamapetugas)
                            .addComponent(tpassword)
                            .addComponent(talamat)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tkdpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnamapetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbjkpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblbatal)
                    .addComponent(tblsimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblsimpanActionPerformed
        // TODO add your handling code here:
        String msg = "";
       String namaPetugas = tnamapetugas.getText();
       int panjangNama = namaPetugas.length();
       final String regex = "^[a-zA-Z]*$";
       Pattern pattern = Pattern.compile(regex);
       Matcher matcher = pattern.matcher(namaPetugas); 
       String jenisKelamin = (String)cbjkpetugas.getSelectedItem();
       String notelpon = tnotelp.getText();
       String alamat = talamat.getText();
       String pass = tpassword.getText();
       if(panjangNama==0){
        
        msg +="Nama Petugas Tidak Boleh Kosong \n";
        
       }
       if(panjangNama >50){
        
        msg +="Nama Petugas Tidak Boleh Lebih dari 50 Karakter \n";
        
       }
       if(jenisKelamin =="Jenis Kelamin"){
       
        msg +="Harap Memilih Jenis Kelamin \n";
        
       }
       if(notelpon.matches("^[0-9]*$")== false){
       
        msg +="Mohon No Telp diisi dengan Angka \n";
       
       }
       if(notelpon.length()<11){
        
        msg +="No Telp Minimal 11 digit \n";
        
       }
       if(alamat.length()==0){
        
        msg +="Alamat tidak Boleh Kosong \n";
        
       }
       if(pass.length()==0){
//       JOptionPane.showMessageDialog(null,"Password Tidak Boleh Kosong");
       msg +="Password Tidak Boleh Kosong \n";
       
       }
       if(msg==""){
        db.update_petugas(new Petugas(tkdpetugas.getText(),tnamapetugas.getText(),(String)cbjkpetugas.getSelectedItem(),
        tnotelp.getText(),talamat.getText(),tpassword.getText()));
        JOptionPane.showMessageDialog(null, "Data Petugas Berhasil Disimpan.");
        setVisible(false);
       }else{
            JOptionPane.showMessageDialog(null,msg);
       }
    }//GEN-LAST:event_tblsimpanActionPerformed

    private void tblbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblbatalActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_tblbatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cbjkpetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField talamat;
    private javax.swing.JButton tblbatal;
    private javax.swing.JButton tblsimpan;
    public javax.swing.JTextField tkdpetugas;
    public javax.swing.JTextField tnamapetugas;
    public javax.swing.JTextField tnotelp;
    public javax.swing.JTextField tpassword;
    // End of variables declaration//GEN-END:variables
}
