/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
/**
 *
 * @author Hilman
 */
import Class.Petugas;
import Class.Petugas.petugasTableModel;
import Koneksi.koneksi;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
public class frmPetugas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPetugas
     */
    public frmPetugas() {
        initComponents();
        tampildata();
    }
    Petugas db = new Petugas();
    Petugas.petugasTableModel tabelpetugas = db.new petugasTableModel();
    
    public void tampildata(){
        tabelpetugas.setData(db.tampil_semua_petugas());
        tblPetugas.setModel(tabelpetugas);
    }
    public void refreshdata(){
        tabelpetugas.setData(db.tampil_semua_petugas());
        tabelpetugas.fireTableDataChanged();
        tblPetugas.changeSelection(0, 0, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPetugas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tbltambah = new javax.swing.JButton();
        tbledit = new javax.swing.JButton();
        tblhapus = new javax.swing.JButton();
        tblrefresh = new javax.swing.JButton();
        tblcari = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();

        setClosable(true);

        tblPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Petugas", "Nama Petugas", "Jenis Kelamin", "No Telepon", "Alamat", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblPetugas);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENGOLAHAN DATA PETUGAS");

        tbltambah.setText("TAMBAH");
        tbltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbltambahActionPerformed(evt);
            }
        });

        tbledit.setText("EDIT");
        tbledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbleditActionPerformed(evt);
            }
        });

        tblhapus.setText("HAPUS");
        tblhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblhapusActionPerformed(evt);
            }
        });

        tblrefresh.setText("REFRESH");
        tblrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblrefreshActionPerformed(evt);
            }
        });

        tblcari.setText("CARI");
        tblcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblcariActionPerformed(evt);
            }
        });

        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblhapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbledit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbltambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblrefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tblcari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1)
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbltambah)
                        .addGap(18, 18, 18)
                        .addComponent(tbledit)
                        .addGap(18, 18, 18)
                        .addComponent(tblhapus)
                        .addGap(18, 18, 18)
                        .addComponent(tblrefresh)
                        .addGap(18, 18, 18)
                        .addComponent(tblcari)
                        .addGap(18, 18, 18)
                        .addComponent(btncetak)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbltambahActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frmTambahPetugas tambahpetugas = new frmTambahPetugas(frame, true);
        tambahpetugas.setVisible(true);
        tambahpetugas.tkdpetugas.setText("");
        tambahpetugas.tnamapetugas.setText("");
        tambahpetugas.cbjkpetugas.setSelectedItem("");
        tambahpetugas.tnotelp.setText("");
        tambahpetugas.talamat.setText("");
        tambahpetugas.tpassword.setText("");
        refreshdata();
    }//GEN-LAST:event_tbltambahActionPerformed

    private void tblrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblrefreshActionPerformed
        // TODO add your handling code here:
        refreshdata();
    }//GEN-LAST:event_tblrefreshActionPerformed

    private void tblhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblhapusActionPerformed
        // TODO add your handling code here:
        try
        {
            int baris = tblPetugas.getSelectedRow();
            String kdPetugas = (String)tabelpetugas.getValueAt(baris, 0);
            String namaPetugas = (String)tabelpetugas.getValueAt(baris, 1);
            Object[] pilihan ={"Ya","Tidak"};
            int jawaban = JOptionPane.showOptionDialog(null,"Anda yakin data "
                    +"Petugas dengan Kode "+kdPetugas+" dengan nama "+namaPetugas+
                    " akan dihapus ?","Peringatan",JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,null,pilihan,pilihan[0]);
            if(jawaban==0)
            {
                db.hapus_petugas(kdPetugas);
                refreshdata();
            }
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null,"pilih data yang ingin dihapus !!!");
        }
    }//GEN-LAST:event_tblhapusActionPerformed

    private void tbleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbleditActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frmEditPetugas editpetugas = new frmEditPetugas(frame, true);
        
        try 
        {
            int baris = tblPetugas.getSelectedRow();
            String kdPetugas = (String) tabelpetugas.getValueAt(baris,0);
            Petugas p = db.pilih_petugas(kdPetugas);
            if(p!=null){
                editpetugas.setForm(p);
                editpetugas.setVisible(true);
                refreshdata();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Petugas dengan Kode "+kdPetugas+
                        " tidak ditemukan");
            }
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diedit!");
        }
    }//GEN-LAST:event_tbleditActionPerformed

    private void tblcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblcariActionPerformed
        // TODO add your handling code here:
        String katakunci;
        katakunci=JOptionPane.showInputDialog(null,"Nama Petugas yang dicari ?",
                "Filter/Pencarian",JOptionPane.QUESTION_MESSAGE);
        if(katakunci!=null)
        {
            tabelpetugas.setData(db.filter_petugas(katakunci));
            tabelpetugas.fireTableDataChanged();
        }
    }//GEN-LAST:event_tblcariActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = koneksi.getKoneksi();
            HashMap param = new HashMap();
            
            JasperReport jr = JasperCompileManager.compileReport("src/Laporan/laporanPetugas.jrxml"); 
            JasperPrint jp = JasperFillManager.fillReport(jr,param,conn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error Karena : "+e.getMessage());
        }
    }//GEN-LAST:event_btncetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPetugas;
    private javax.swing.JButton tblcari;
    private javax.swing.JButton tbledit;
    private javax.swing.JButton tblhapus;
    private javax.swing.JButton tblrefresh;
    private javax.swing.JButton tbltambah;
    // End of variables declaration//GEN-END:variables
}
