/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Class.Petugas;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Hilman
 */
public class frmTambahPetugas extends javax.swing.JDialog {
    Petugas db = new Petugas();
    /**
     * Creates new form frmTambahPetugas
     */
    public frmTambahPetugas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null); 
        initComponents();
        tkdpetugas.setText(db.id_otomatis());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tkdpetugas = new javax.swing.JTextField();
        tnamapetugas = new javax.swing.JTextField();
        tnotelp = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        tpassword = new javax.swing.JTextField();
        cbjkpetugas = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tblBatal = new javax.swing.JButton();
        tblSimpan = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Petugas");

        jLabel2.setText("Nama Petugas");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("No Telepon");

        jLabel5.setText("Alamat");

        jLabel6.setText("Password");

        tkdpetugas.setEditable(false);

        cbjkpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Kelamin", "L", "P" }));

        jLabel7.setText("TAMBAH DATA PETUGAS");

        tblBatal.setText("Batal");
        tblBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBatalActionPerformed(evt);
            }
        });

        tblSimpan.setText("Simpan");
        tblSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tblSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(tblBatal))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbjkpetugas, 0, 217, Short.MAX_VALUE)
                            .addComponent(tkdpetugas)
                            .addComponent(tnotelp)
                            .addComponent(tnamapetugas)
                            .addComponent(tpassword)
                            .addComponent(talamat)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tkdpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnamapetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbjkpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblBatal)
                    .addComponent(tblSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSimpanActionPerformed
        // TODO add your handling code here:
       String msg = "";
       String namaPetugas = tnamapetugas.getText();
       int panjangNama = namaPetugas.length();
       final String regex = "^[a-zA-Z]*$";
       Pattern pattern = Pattern.compile(regex);
       Matcher matcher = pattern.matcher(namaPetugas); 
       String jenisKelamin = (String)cbjkpetugas.getSelectedItem();
       String notelpon = tnotelp.getText();
       String alamat = talamat.getText();
       String pass = tpassword.getText();
       if(panjangNama==0){       
        msg +="Nama Petugas Tidak Boleh Kosong \n";        
       }
       if(panjangNama >50){
        
        msg +="Nama Petugas Tidak Boleh Lebih dari 50 Karakter \n";
        
       }
       if(jenisKelamin =="Jenis Kelamin"){
       
        msg +="Harap Memilih Jenis Kelamin \n";
        
       }
       if(notelpon.matches("^[0-9]*$")== false){
       
        msg +="Mohon No Telp diisi dengan Angka \n";
       
       }
       if(notelpon.length()<11){
        
        msg +="No Telp Minimal 11 digit \n";
        
       }
       if(alamat.length()==0){
        
        msg +="Alamat tidak Boleh Kosong \n";
        
       }
       if(pass.length()==0){
//       JOptionPane.showMessageDialog(null,"Password Tidak Boleh Kosong");
       msg +="Password Tidak Boleh Kosong \n";
       
       }
        
    if(msg==""){
     db.tambah_petugas(new Petugas(tkdpetugas.getText(),tnamapetugas.getText(),(String)cbjkpetugas.getSelectedItem(),
    tnotelp.getText(),talamat.getText(),tpassword.getText()));
    JOptionPane.showMessageDialog(null, "Data Petugas Berhasil Disimpan.");
    setVisible(false);   
    }else{   
       JOptionPane.showMessageDialog(null,msg);
    }    
        
    }//GEN-LAST:event_tblSimpanActionPerformed

    private void tblBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBatalActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_tblBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cbjkpetugas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JTextField talamat;
    private javax.swing.JButton tblBatal;
    private javax.swing.JButton tblSimpan;
    public javax.swing.JTextField tkdpetugas;
    public javax.swing.JTextField tnamapetugas;
    public javax.swing.JTextField tnotelp;
    public javax.swing.JTextField tpassword;
    // End of variables declaration//GEN-END:variables
}
