/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Class.Customer;
import Koneksi.koneksi;
import java.sql.Connection;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Arrays;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author VexL
 */
public class frmTambahCustomer extends javax.swing.JDialog {

    /**
     * Creates new form frmTambahTransaksi
     */ 
    Customer cst = new Customer();
    
    public frmTambahCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setTitle("Tambah Customer");
        this.setLocationRelativeTo(null);       
              
        txtKdCst.setText(idOtomatis());      
    }
 
//    NOMOR OTOMATIS
    public String idOtomatis() {
        Connection conn = null;
        Statement stmt = null;
        String kdCustomerNew = "";
         try {
            conn = koneksi.getKoneksi();
            String sql = "SELECT * FROM customer ORDER BY kdCustomer DESC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String kdCustomer = rs.getString("kdCustomer").substring(1);
                String AN = "" + (Integer.parseInt(kdCustomer) + 1);
                String Nol = "";

                if(AN.length()==1)
                    {Nol = "00";
                }else if(AN.length()==2){
                    Nol = "0";
                }else if(AN.length()==3){
                    Nol = "";
                }
                kdCustomerNew = "C"+Nol+AN;
            } else {
                kdCustomerNew = "C001";
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally {
            try {
                stmt.close();
            } catch(Exception e) {}
            try {
                conn.close();
            } catch(Exception e) {}
            
        }
        return kdCustomerNew;
    }
    
//    PILIHAN KURSI
    public String pilihJk()
    {
        String jk = "";
        if(radioL.isSelected()){
            jk = "L";
        } else if(radioP.isSelected()){
            jk = "P";
        }; 
        return jk;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jkGroup = new javax.swing.ButtonGroup();
        lblAddCst = new javax.swing.JLabel();
        lblKdCst = new javax.swing.JLabel();
        lblNamaCst = new javax.swing.JLabel();
        lblJkCst = new javax.swing.JLabel();
        lblAlamatCst = new javax.swing.JLabel();
        lblNotelpCst = new javax.swing.JLabel();
        txtNamaCst = new javax.swing.JTextField();
        txtAlamatCst = new javax.swing.JTextField();
        txtNotelpCst = new javax.swing.JTextField();
        radioL = new javax.swing.JRadioButton();
        radioP = new javax.swing.JRadioButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtKdCst = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAddCst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddCst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddCst.setText("TAMBAH CUSTOMER TRAVEL");

        lblKdCst.setText("Kode Customer");

        lblNamaCst.setText("Nama");

        lblJkCst.setText("Jenis Kelamin");

        lblAlamatCst.setText("Alamat");

        lblNotelpCst.setText("No. Telp");

        jkGroup.add(radioL);
        radioL.setText("Laki-laki");

        jkGroup.add(radioP);
        radioP.setText("Perempuan");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        txtKdCst.setEditable(false);
        txtKdCst.setToolTipText("");

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddCst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNotelpCst)
                        .addGap(65, 65, 65)
                        .addComponent(txtNotelpCst))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKdCst)
                            .addComponent(lblNamaCst)
                            .addComponent(lblJkCst)
                            .addComponent(lblAlamatCst))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAlamatCst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(txtNamaCst, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(radioL)
                                .addGap(18, 18, 18)
                                .addComponent(radioP))
                            .addComponent(txtKdCst, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblAddCst)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKdCst)
                    .addComponent(txtKdCst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaCst)
                    .addComponent(txtNamaCst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJkCst)
                    .addComponent(radioL)
                    .addComponent(radioP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlamatCst)
                    .addComponent(txtAlamatCst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotelpCst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotelpCst))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal)
                    .addComponent(btnReset))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String kdCustomer = txtKdCst.getText();
        String namaCustomer = txtNamaCst.getText();
        String alamatCustomer = txtAlamatCst.getText();
        String notelpCustomer = txtNotelpCst.getText();
        
        if("".equals(kdCustomer) || "Nama Customer".equals(namaCustomer) || jkGroup.getSelection() == null || "Alamat Customer".equals(alamatCustomer) || "No. Telp".equals(notelpCustomer))
        {
            JOptionPane.showMessageDialog(null, "Masukan harus terisi semua!");
        } else {
            String jkCst = pilihJk();
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menyimpan data?","Konfirmasi", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                cst.tambahCustomer(new Customer(kdCustomer, namaCustomer, jkCst, alamatCustomer, notelpCustomer));
                JOptionPane.showMessageDialog(null, "Data Customer Berhasil Disimpan.");
                setVisible(false);  
            }         
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNamaCst.setText("");
        jkGroup.clearSelection();
        txtAlamatCst.setText("");
        txtNotelpCst.setText("");
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.ButtonGroup jkGroup;
    private javax.swing.JLabel lblAddCst;
    private javax.swing.JLabel lblAlamatCst;
    private javax.swing.JLabel lblJkCst;
    private javax.swing.JLabel lblKdCst;
    private javax.swing.JLabel lblNamaCst;
    private javax.swing.JLabel lblNotelpCst;
    private javax.swing.JRadioButton radioL;
    private javax.swing.JRadioButton radioP;
    private javax.swing.JTextField txtAlamatCst;
    public javax.swing.JTextField txtKdCst;
    private javax.swing.JTextField txtNamaCst;
    private javax.swing.JTextField txtNotelpCst;
    // End of variables declaration//GEN-END:variables
}
