package Form;


import Class.Login;
import Koneksi.koneksi;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salma
 */
public class frmUtama extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    Login login = new Login();
    public frmUtama(String petugas) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        lbpetugas.setText(petugas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lbpetugas = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPetugas = new javax.swing.JButton();
        btnKeberangkatan = new javax.swing.JButton();
        btnTujuan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnPemesanan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnPemesanan1 = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnKeluarAkun = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnKeluarAplikasi = new javax.swing.JMenuItem();
        mnKelolaData = new javax.swing.JMenu();
        mnCustomer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnPetugas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnKeberangkatan = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnTujuan = new javax.swing.JMenuItem();
        kelolaTrs = new javax.swing.JMenu();
        mnPemesanan = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        mnLapCst = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnLapPtg = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnLapKbr = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnLapTjn = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnLapTrans = new javax.swing.JMenuItem();
        mnClearMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbpetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpetugas.setText("[petugas]");

        btnCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnCustomer.setText(" CUSTOMER");
        btnCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TRANSAKSI");

        btnPetugas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnPetugas.setText(" PETUGAS");
        btnPetugas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetugasActionPerformed(evt);
            }
        });

        btnKeberangkatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKeberangkatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titik.png"))); // NOI18N
        btnKeberangkatan.setText("KEBERANGKATAN");
        btnKeberangkatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKeberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeberangkatanActionPerformed(evt);
            }
        });

        btnTujuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTujuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titik.png"))); // NOI18N
        btnTujuan.setText(" TUJUAN");
        btnTujuan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTujuanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("KELOLA DATA");

        btnPemesanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receipt.png"))); // NOI18N
        btnPemesanan.setText(" PESANAN");
        btnPemesanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesananActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AKUN");

        btnPemesanan1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPemesanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keluar.png"))); // NOI18N
        btnPemesanan1.setText(" LOG OUT");
        btnPemesanan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPemesanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesanan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbpetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTujuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKeberangkatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPemesanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPemesanan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbpetugas)
                .addGap(46, 46, 46)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPemesanan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel3)
                    .addContainerGap(516, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mnFile.setText("File");
        mnFile.add(jSeparator9);

        mnKeluarAkun.setText("Keluar Akun");
        mnKeluarAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarAkunActionPerformed(evt);
            }
        });
        mnFile.add(mnKeluarAkun);
        mnFile.add(jSeparator10);

        mnKeluarAplikasi.setText("Keluar Aplikasi");
        mnKeluarAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarAplikasiActionPerformed(evt);
            }
        });
        mnFile.add(mnKeluarAplikasi);

        jMenuBar1.add(mnFile);

        mnKelolaData.setText("Kelola Data");

        mnCustomer.setText("Customer");
        mnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCustomerActionPerformed(evt);
            }
        });
        mnKelolaData.add(mnCustomer);
        mnKelolaData.add(jSeparator1);

        mnPetugas.setText("Petugas");
        mnPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPetugasActionPerformed(evt);
            }
        });
        mnKelolaData.add(mnPetugas);
        mnKelolaData.add(jSeparator2);

        mnKeberangkatan.setText("Keberangkatan");
        mnKeberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeberangkatanActionPerformed(evt);
            }
        });
        mnKelolaData.add(mnKeberangkatan);
        mnKelolaData.add(jSeparator3);

        mnTujuan.setText("Tujuan");
        mnTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTujuanActionPerformed(evt);
            }
        });
        mnKelolaData.add(mnTujuan);

        jMenuBar1.add(mnKelolaData);

        kelolaTrs.setText("Kelola Transaksi");

        mnPemesanan.setText("Pemesanan");
        mnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPemesananActionPerformed(evt);
            }
        });
        kelolaTrs.add(mnPemesanan);

        jMenuBar1.add(kelolaTrs);

        mnLaporan.setText("Laporan");

        mnLapCst.setText("Laporan Customer");
        mnLapCst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapCstActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapCst);
        mnLaporan.add(jSeparator4);

        mnLapPtg.setText("Laporan Petugas");
        mnLapPtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPtgActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapPtg);
        mnLaporan.add(jSeparator5);

        mnLapKbr.setText("Laporan Keberangkatan");
        mnLapKbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapKbrActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapKbr);
        mnLaporan.add(jSeparator8);

        mnLapTjn.setText("Laporan Tujuan");
        mnLapTjn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapTjnActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapTjn);
        mnLaporan.add(jSeparator7);

        mnLapTrans.setText("Laporan Transaksi");
        mnLapTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapTransActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapTrans);

        jMenuBar1.add(mnLaporan);

        mnClearMenu.setText("Clear Menu");
        mnClearMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnClearMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnClearMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCustomerActionPerformed
        frmCst customer = new frmCst();
        desktop.add(customer);
        Dimension layardesktop = this.getSize();
        Dimension layarcst = customer.getSize();
        customer.setLocation((int)layardesktop.getWidth()/2-(int)layarcst.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layarcst.getHeight()/2);
        customer.setVisible(true);
    }//GEN-LAST:event_mnCustomerActionPerformed

    private void mnKeberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeberangkatanActionPerformed
        frmKeberangkatan kbr = new frmKeberangkatan();
        desktop.add(kbr);
        Dimension layardesktop = this.getSize();
        Dimension layartrs = kbr.getSize();
        kbr.setLocation((int)layardesktop.getWidth()/2-(int)layartrs.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layartrs.getHeight()/2);
        kbr.setVisible(true);
    }//GEN-LAST:event_mnKeberangkatanActionPerformed

    private void mnKeluarAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarAplikasiActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnKeluarAplikasiActionPerformed

    private void mnLapCstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapCstActionPerformed
        try {
            Connection conn = koneksi.getKoneksi();
//            File file = new File("src/Laporan/LaporanTransaksi.jasper");
            HashMap param = new HashMap();

            JasperReport jr = JasperCompileManager.compileReport("src/Laporan/LaporanCustomer.jrxml");
            JasperPrint jp = JasperFillManager.fillReport(jr, param, conn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error karena:"+e.getMessage());
        }
    }//GEN-LAST:event_mnLapCstActionPerformed

    private void mnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPemesananActionPerformed
        frmTrs transaksi = new frmTrs();
        desktop.add(transaksi);
        Dimension layardesktop = this.getSize();
        Dimension layartrs = transaksi.getSize();
        transaksi.setLocation((int)layardesktop.getWidth()/2-(int)layartrs.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layartrs.getHeight()/2);
        transaksi.setVisible(true);
    }//GEN-LAST:event_mnPemesananActionPerformed

    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        frmTrs transaksi = new frmTrs();
        desktop.add(transaksi);
        Dimension layardesktop = this.getSize();
        Dimension layartrs = transaksi.getSize();
        transaksi.setLocation((int)layardesktop.getWidth()/2-(int)layartrs.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layartrs.getHeight()/2);
        transaksi.setVisible(true);
    }//GEN-LAST:event_btnPemesananActionPerformed

    private void btnKeberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeberangkatanActionPerformed
        frmKeberangkatan kbr = new frmKeberangkatan();
        desktop.add(kbr);
        Dimension layardesktop = this.getSize();
        Dimension layartrs = kbr.getSize();
        kbr.setLocation((int)layardesktop.getWidth()/2-(int)layartrs.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layartrs.getHeight()/2);
        kbr.setVisible(true);
    }//GEN-LAST:event_btnKeberangkatanActionPerformed

    private void btnTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTujuanActionPerformed
        frmTujuan tujuan = new frmTujuan();
        desktop.add(tujuan);
        Dimension layardesktop = this.getSize();
        Dimension layartrs = tujuan.getSize();
        tujuan.setLocation((int)layardesktop.getWidth()/2-(int)layartrs.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layartrs.getHeight()/2);
        tujuan.setVisible(true);
    }//GEN-LAST:event_btnTujuanActionPerformed

    private void mnTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTujuanActionPerformed
        frmTujuan tujuan = new frmTujuan();
        desktop.add(tujuan);
        Dimension layardesktop = this.getSize();
        Dimension layartrs = tujuan.getSize();
        tujuan.setLocation((int)layardesktop.getWidth()/2-(int)layartrs.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layartrs.getHeight()/2);
        tujuan.setVisible(true);
    }//GEN-LAST:event_mnTujuanActionPerformed

    private void btnPemesanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesanan1ActionPerformed
        frmLogin f_login = new frmLogin();
        setVisible(false);
        f_login.setVisible(true);
    }//GEN-LAST:event_btnPemesanan1ActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        frmCst customer = new frmCst();
        desktop.add(customer);
        Dimension layardesktop = this.getSize();
        Dimension layarcst = customer.getSize();
        customer.setLocation((int)layardesktop.getWidth()/2-(int)layarcst.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layarcst.getHeight()/2);
        customer.setVisible(true);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void mnLapTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapTransActionPerformed
        try {
            Connection conn = koneksi.getKoneksi();
//            File file = new File("src/Laporan/LaporanTransaksi.jasper");
            HashMap param = new HashMap();

            JasperReport jr = JasperCompileManager.compileReport("src/Laporan/LaporanTransaksi.jrxml");
            JasperPrint jp = JasperFillManager.fillReport(jr, param, conn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error karena:"+e.getMessage());
        }
    }//GEN-LAST:event_mnLapTransActionPerformed

    private void mnPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPetugasActionPerformed
        frmPetugas petugas = new frmPetugas();
        desktop.add(petugas);
        Dimension layardesktop = this.getSize();
        Dimension layarcst = petugas.getSize();
        petugas.setLocation((int)layardesktop.getWidth()/2-(int)layarcst.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layarcst.getHeight()/2);
        petugas.setVisible(true);
    }//GEN-LAST:event_mnPetugasActionPerformed

    private void mnLapPtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPtgActionPerformed
        try {
            Connection conn = koneksi.getKoneksi();
            HashMap param = new HashMap();
            
            JasperReport jr = JasperCompileManager.compileReport("src/Laporan/laporanPetugas.jrxml"); 
            JasperPrint jp = JasperFillManager.fillReport(jr,param,conn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error Karena : "+e.getMessage());
        }
    }//GEN-LAST:event_mnLapPtgActionPerformed

    private void btnPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetugasActionPerformed
        frmPetugas petugas = new frmPetugas();
        desktop.add(petugas);
        Dimension layardesktop = this.getSize();
        Dimension layarcst = petugas.getSize();
        petugas.setLocation((int)layardesktop.getWidth()/2-(int)layarcst.getWidth()/2,
                              (int)layardesktop.getHeight()/2-(int)layarcst.getHeight()/2);
        petugas.setVisible(true);
    }//GEN-LAST:event_btnPetugasActionPerformed

    private void mnLapKbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapKbrActionPerformed
        try {
            Connection conn = koneksi.getKoneksi();
            HashMap param = new HashMap();
            
            JasperReport jr = JasperCompileManager.compileReport("src/Laporan/laporanKeberangkatan.jrxml"); 
            JasperPrint jp = JasperFillManager.fillReport(jr,param,conn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error Karena : "+e.getMessage());
        }
    }//GEN-LAST:event_mnLapKbrActionPerformed

    private void mnLapTjnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapTjnActionPerformed
        try {
            Connection conn = koneksi.getKoneksi();
            HashMap param = new HashMap();
            
            JasperReport jr = JasperCompileManager.compileReport("src/Laporan/laporanTujuan.jrxml"); 
            JasperPrint jp = JasperFillManager.fillReport(jr,param,conn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error Karena : "+e.getMessage());
        }
    }//GEN-LAST:event_mnLapTjnActionPerformed

    private void mnKeluarAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarAkunActionPerformed
        frmLogin f_login = new frmLogin();
        setVisible(false);
        f_login.setVisible(true);
    }//GEN-LAST:event_mnKeluarAkunActionPerformed

    private void mnClearMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnClearMenuMouseClicked
        desktop.removeAll();
        desktop.repaint();
    }//GEN-LAST:event_mnClearMenuMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnKeberangkatan;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnPemesanan1;
    private javax.swing.JButton btnPetugas;
    private javax.swing.JButton btnTujuan;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu kelolaTrs;
    private javax.swing.JLabel lbpetugas;
    private javax.swing.JMenu mnClearMenu;
    private javax.swing.JMenuItem mnCustomer;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnKeberangkatan;
    private javax.swing.JMenu mnKelolaData;
    private javax.swing.JMenuItem mnKeluarAkun;
    private javax.swing.JMenuItem mnKeluarAplikasi;
    private javax.swing.JMenuItem mnLapCst;
    private javax.swing.JMenuItem mnLapKbr;
    private javax.swing.JMenuItem mnLapPtg;
    private javax.swing.JMenuItem mnLapTjn;
    private javax.swing.JMenuItem mnLapTrans;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenuItem mnPemesanan;
    private javax.swing.JMenuItem mnPetugas;
    private javax.swing.JMenuItem mnTujuan;
    // End of variables declaration//GEN-END:variables
}
